spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false

batch:
  outDirectory: '//Users/mtoure/dev/bnp/spring-batch-csv-partition/src/main/resources/data'
  intDirectory: '//Users/mtoure/dev/bnp/spring-batch-csv-partition/src/main/resources/data'
#
# CONFIGURATION TAILLE DES LOTS
# ----------------------------------------------------------------------------------------------------------------------
step:
  chunk:
    size: 1
  skip:
    limit: 5
